config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :plays do
    resources :reviews
  end
  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plays
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
# frozen_string_literal: true

class PlaysController < ApplicationController
  before_action :find_play, only: %i[show edit update destroy]
  before_action :get_categories, only: %i[new edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(category_id: @category_id).order('created_at DESC')
    end
  end

  def new
    @play = current_user.plays.build
  end

  def show; end

  def create
    @play = current_user.plays.build(play_params)
    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :director, :image, :category_id)
  end

  def find_play
    @play = Play.find(params[:id])
  end

  def get_categories
    @categories = Category.all.map do |category|
      [category.name, category.id]
    end
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: %i[edit update destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def find_play
    @play = Play.find(params[:play_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Broadway", root_path, class: "navbar-brand"  %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres <span class="caret"></span></a>

					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, plays_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>
          <% if user_signed_in? %>
            <li><%= link_to "Add Play", new_play_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play, html: {multipart: true} do |f| %>
  <%= f.file_field :image %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.select :category_id, @categories, :prompt => "Select Category" %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit Broadplay Play</h1>

<%= render 'form' %>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count.zero? %>
	<h3>There are no plays in this category</h3>
<% else %>
	<div class="row">
		<% @plays.each do |play| %>
			<div class="col-md-3">
        <%= link_to play_path(play) do %>
					<%= image_tag play.image.variant(resize_to_limit: [250, 350]), class: "play" %>
					<h2><%= play.title %></h2>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/plays/new.html.erb
<h1>New Broadplay Play</h1>

<%= render 'form' %>

app/views/plays/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @play.image.variant(resize_to_limit: [325, 475]), class: "play-show" %>
	</div>

	<div class="col-md-8">
		<div class="col-md-8">
			<div class="play-info">
				<h2 class="play-title"><%= @play.title %></h2>
				<h3 class="play-director"><span><em>From: </em></span><%= @play.director %></h3>
				<h4 class="play-category"><%= @play.category.name %></h4>
				<p class="play-desc"><%= @play.description %></p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="reviews">
			<h1> Reviews </h1>
				<%= render @play.reviews %>
				<div>
					<%= link_to "Add Reviews", new_play_review_path(@play), class: "btn-custom" %>
				</div>
		</div>
	</div>
</div>


<div class="links btn-group">
	<% if user_signed_in? %>
		<% if @play.user_id == current_user.id %>
			<%= link_to "Edit", edit_play_path(@play), class: "btn btn-custom" %>
			<%= link_to "Delete", play_path(@play), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
		<% end %>
	<% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
	<div id="rating-form">
		<label> Rating </label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_play_review_path(review.play, review), class: "btn btn-custom" %>
				<%= link_to "Delete", play_review_path(review.play, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="edit-review-form">
		<h1> Edit Review </h1>
			<%= simple_form_for([@play, @review]) do |f| %>
				<div id="rating-form">
					<label> Rating </label>
				</div>
				<%= f.input :comment %>
				<%= f.button :submit, :class => "btn-custom2" %>
			<% end %>
	</div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="new-review-form">
		<h1> Post Review </h1>
		<%= render 'form' %>
	</div>
</div>